name: Notify

on:
  workflow_run:
    workflows: ["CI", "CD"]
    types: [completed]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check workflow result
      id: check-result
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi
        
    - name: Notify on success
      if: steps.check-result.outputs.status == 'success'
      run: |
        echo "✅ Workflow completed successfully!"
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Branch: ${{ github.event.workflow_run.head_branch }}"
        
    - name: Notify on failure
      if: steps.check-result.outputs.status == 'failure'
      run: |
        echo "❌ Workflow failed!"
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Branch: ${{ github.event.workflow_run.head_branch }}"
        echo "Check the logs for details."
